'use strict';

const fs   = require('fs');
const path = require('path');

/**
 * Robust .env parser — handles:
 *   KEY=value
 *   KEY="double quoted"          → strips quotes, processes \n \" escapes
 *   KEY='single quoted'          → strips quotes, no escape processing
 *   KEY=value # inline comment   → strips comment
 *   Multi-line double-quoted values
 *   export KEY=value             → strips export prefix
 *   Windows \r\n line endings
 *   Blank lines and # full-line comments
 *
 * @param {string} filePath
 * @returns {Record<string, string>}
 */
function parseEnvFile(filePath) {
  if (!fs.existsSync(filePath)) return {};

  // Normalise Windows line endings before splitting
  const content = fs.readFileSync(filePath, 'utf-8').replace(/\r\n/g, '\n').replace(/\r/g, '\n');
  const result  = {};
  const lines   = content.split('\n');

  let i = 0;
  while (i < lines.length) {
    let line = lines[i].trim();
    i++;

    if (!line || line.startsWith('#')) continue;
    if (line.startsWith('export ')) line = line.slice(7).trim();

    const eqIdx = line.indexOf('=');
    if (eqIdx === -1) continue;

    const key = line.slice(0, eqIdx).trim();
    if (!key || !/^[A-Z_][A-Z0-9_]*$/i.test(key)) continue;

    let value = line.slice(eqIdx + 1);

    // ── Double-quoted (multi-line aware) ────────────────────────────────────
    if (value.startsWith('"')) {
      let inner = value.slice(1);
      // Collect continuation lines until we find an unescaped closing quote
      while (i < lines.length) {
        const closeIdx = findUnescapedQuote(inner, '"');
        if (closeIdx !== -1) {
          inner = inner.slice(0, closeIdx);
          break;
        }
        inner += '\n' + lines[i];
        i++;
      }
      value = inner
        .replace(/\\n/g, '\n')
        .replace(/\\r/g, '\r')
        .replace(/\\t/g, '\t')
        .replace(/\\"/g, '"')
        .replace(/\\\\/g, '\\');
    }
    // ── Single-quoted (literal, no escapes) ─────────────────────────────────
    else if (value.startsWith("'")) {
      const closeIdx = value.indexOf("'", 1);
      value = closeIdx !== -1 ? value.slice(1, closeIdx) : value.slice(1);
    }
    // ── Unquoted: strip inline comment ──────────────────────────────────────
    else {
      // Only strip " #" (space before hash) to avoid breaking URLs with #fragment
      const commentIdx = value.search(/ #/);
      if (commentIdx !== -1) value = value.slice(0, commentIdx);
      value = value.trim();
    }

    result[key] = value;
  }

  return result;
}

/**
 * Find the index of an unescaped quote character in a string.
 * @param {string} str
 * @param {string} quote
 * @returns {number} index or -1
 */
function findUnescapedQuote(str, quote) {
  for (let i = 0; i < str.length; i++) {
    if (str[i] === '\\') { i++; continue; } // skip escaped char
    if (str[i] === quote) return i;
  }
  return -1;
}

/**
 * Generate a .env.example file from a schema.
 * Includes type, required status, default, pattern hint, and example value.
 *
 * @param {Record<string, object>} schema
 * @param {string} [outputPath]
 * @returns {string}
 */
function generateEnvExample(schema, outputPath) {
  const lines = [
    '# ─── Auto-generated by env-guard ───────────────────────────────────────────',
    '# Do not commit real secrets. Fill in values before running the application.',
    '',
  ];

  for (const [key, field] of Object.entries(schema)) {
    if (field.description) {
      lines.push(`# ${field.description}`);
    }

    const required = field.required !== false && field.default === undefined;
    lines.push(`# Type: ${field.type} | ${required ? 'required' : 'optional'}`);

    if (field.enum) {
      lines.push(`# Allowed values: ${field.enum.join(' | ')}`);
    }
    if (field.pattern) {
      lines.push(`# Pattern: ${field.pattern.toString()}`);
    }
    if (field.minLength !== undefined || field.maxLength !== undefined) {
      const parts = [];
      if (field.minLength !== undefined) parts.push(`min ${field.minLength} chars`);
      if (field.maxLength !== undefined) parts.push(`max ${field.maxLength} chars`);
      lines.push(`# Length: ${parts.join(', ')}`);
    }
    if (field.min !== undefined || field.max !== undefined) {
      const parts = [];
      if (field.min !== undefined) parts.push(`min ${field.min}`);
      if (field.max !== undefined) parts.push(`max ${field.max}`);
      lines.push(`# Range: ${parts.join(', ')}`);
    }
    if (field.protocols) {
      lines.push(`# Protocols: ${field.protocols.join(', ')}`);
    }
    if (field.default !== undefined) {
      lines.push(`# Default: ${JSON.stringify(field.default)}`);
    }

    const exampleValue = field.example !== undefined
      ? field.example
      : field.default !== undefined ? String(field.default) : '';

    lines.push(`${key}=${exampleValue}`);
    lines.push('');
  }

  const content = lines.join('\n');

  if (outputPath) {
    fs.writeFileSync(path.resolve(outputPath), content, 'utf-8');
  }

  return content;
}

module.exports = { parseEnvFile, generateEnvExample };